# Generated by Django 3.1.5 on 2021-02-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='File',
        ),
    ]
