# Generated by Django 3.1.5 on 2021-02-20 08:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0002_remove_upload_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='File',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='email',
            field=models.EmailField(help_text='Please describe your project', max_length=254),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='example',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
