# Generated by Django 3.1.5 on 2021-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210129_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
