# Generated by Django 3.1.5 on 2021-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_postarticle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
