# Generated by Django 3.1.5 on 2021-01-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210130_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postarticle',
            name='file',
        ),
    ]
