# Generated by Django 3.1.5 on 2021-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_postarticle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='file',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
