# Generated by Django 3.1.5 on 2021-02-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
