# Generated by Django 3.1.5 on 2021-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_postarticle_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='image_field',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
