# Generated by Django 3.1.5 on 2021-03-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_postarticle_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postarticle',
            name='likes',
        ),
    ]
